apiVersion: v1
kind: Namespace
metadata:
  name: nav-integration
  labels:
    name: nav-integration
    purpose: enterprise-integration-platform
---
# ConfigMap for shared configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nav-integration-config
  namespace: nav-integration
data:
  # Database configuration
  POSTGRES_DB: "navdb"
  POSTGRES_USER: "nav"
  
  # Kafka configuration  
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_ENABLED: "true"
  
  # RabbitMQ configuration
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "nav"
  
  # External service URLs (internal cluster communication)
  FOLKEREGISTER_URL: "http://folkeregister-service:8081"
  SKATTEETATEN_URL: "http://skatteetaten-service:8082" 
  BANK_URL: "http://bank-service:8083"
  AORDNINGEN_URL: "http://aordningen-service:8084"
  API_GATEWAY_URL: "http://api-gateway-service:8080"
  
  # Application configuration
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SERVER_PORT: "8080"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,metrics"
  
---
# Secret for sensitive configuration
apiVersion: v1
kind: Secret
metadata:
  name: nav-integration-secrets
  namespace: nav-integration
type: Opaque
data:
  # Base64 encoded values
  POSTGRES_PASSWORD: bmF2cGFzc3dvcmQ=  # navpassword
  RABBITMQ_PASSWORD: bmF2cGFzc3dvcmQ=  # navpassword
  JWT_SECRET: bmF2LXNlY3JldC1rZXktZm9yLWp3dC10b2tlbnM=  # nav-secret-key-for-jwt-tokens